<a href="https://www.kaggle.com/code/yeasminbenin/day-3-variable-statistics-for-datascience?scriptVersionId=343280915" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Classification of Data

## 1. Based on Data Types

- **Numerical Data**: Data that consists of numbers and can be used in mathematical calculations.
  - **Integer**: Whole numbers, such as `10`, `25`, and `-5`
  - **Float**: Decimal numbers, such as `3.14`, `25.5`, and `-0.75`

- **Categorical Data**: Data that represents categories or labels.
  - **Binary**: Contains only two categories, such as `Yes/No` or `0/1`
  - **Nominal**: Categories without a natural order, such as `Red`, `Blue`, and `Green`
  - **Ordinal**: Categories with a meaningful order, such as `Low`, `Medium`, and `High`

- **Text Data**: Data consisting of words, sentences, or other textual information, such as `"Hello World"` or customer reviews.

- **Date/Time Data**: Data representing dates, times, or both, such as `2026-08-18` or `10:30 AM`.

## 2. Based on Measurement Scale

- **Nominal Scale**
- **Ordinal Scale**
- **Interval Scale**
- **Ratio Scale**

## 3. Based on Role in Analysis

- **Independent Variable (Feature/Input)**
- **Dependent Variable (Target/Output)**
- **Control Variable**
- **Confounding Variable**

## 4. Based on the Nature of the Data

- **Discrete Data**
- **Continuous Data**
- **Qualitative Data**
- **Quantitative Data**

## 5. Based on Distribution

- **Normal Distribution**
- **Uniform Distribution**
- **Skewed Distribution**
  - **Positively Skewed**
  - **Negatively Skewed**
- **Bimodal Distribution**
- **Multimodal Distribution**

In [1]:
import pandas as pd

In [7]:
url = "https://raw.githubusercontent.com/byeasmin/Datasets-ML-DL/refs/heads/main/Churn_Modelling.csv"

In [8]:
df = pd.read_csv(url)

In [9]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [10]:
df.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [17]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object